import '@/styles/globals.css'
import '@/styles/customAnimations.css'
import type { AppProps } from 'next/app'
import Modal from 'react-modal';
import Head from 'next/head';
import { useEffect, useRef } from 'react'
import jwt from 'jsonwebtoken';
import { setUserStates } from '@/states/user/utils';
import AOS from 'aos';
import 'aos/dist/aos.css';
import cookie from 'cookie'
import { GetServerSideProps } from 'next';
import { decodeJWT } from '@/utils/helpers';

Modal.setAppElement('#__next')

export default function App({ Component, pageProps }: AppProps) {
  useEffect(() => {
    const populateToken = async () => {
      if(window !== undefined){
        const token = localStorage?.getItem('token') as string
        if(token){
          const decoded = await jwt.decode(token) as jwt.JwtPayload
          const uid = decoded?.result?.id as number ?? undefined
          const email = decoded?.result?.email as string
          const type = decoded?.result?.type as string
          setUserStates(uid, email, token, true, type)
        }
      }
    }
    populateToken()
    AOS.init();
  }, [])
  return <>
    <Head>
      <title>Univtraze App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Component {...pageProps} />
  </>
}